name: theday
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  google_fonts:
  curved_labeled_navigation_bar: ^2.0.2
  flutter_spinkit:
  cached_network_image: ^3.3.1
  intl:
  shared_preferences: ^2.2.2
  google_sign_in: ^6.2.1
  firebase_auth:
  firebase_core: ^3.3.0
  get: 4.6.6
  flutter_launcher_icons: ^0.13.1
  flutter: 
    sdk: flutter
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/theday_logo.png"
  min_sdk_android: 21 # andro
dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
   - assets/
